[package]
name = "bsamples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.1"
anyhow = "1.0.48"
serde = { version =  "1.0.130", features = [ "derive" ] }
serde_json = "1.0.72"
